/*QUERY CALCULO DE GR GZ NUEVAS*/

USE ${SCHEMASPAIS};

IF OBJECT_ID('tempDB..#TEMP_FFVV', 'U') IS NOT NULL
   DROP TABLE #TEMP_FFVV;

IF OBJECT_ID('tempDB..#TEMP_CAMPANA_ASIG', 'U') IS NOT NULL
DROP TABLE #TEMP_CAMPANA_ASIG;

DECLARE @TABLE_CAMPANAS TABLE
(
  ANIOCAMPANA CHAR(6)
);

INSERT INTO @TABLE_CAMPANAS (ANIOCAMPANA)
SELECT A.ANIOCAMPANA
FROM (
SELECT
	ROW_NUMBER() OVER(ORDER BY ANIOCAMPANA DESC) AS Row#
	,ANIOCAMPANA
FROM
	FDIRFFVVCAM
GROUP BY
	ANIOCAMPANA
) A
WHERE A.Row# <= 2;

SELECT
	FDIRFFVVCAM.PKClienteFFVV
	,FDIRFFVVCAM.ANIOCAMPANA
	,DPAIS.CODPAIS
	,DREGIONCAMPANA.CODREGION
	,'' CODZONA
	,DROL.CODROL
	,DCLIENTEFFVV.CUB
	,DCLIENTEFFVV.codClienteFFVV
	,DCLIENTEFFVV.DesApeNom
INTO #TEMP_FFVV
FROM FDIRFFVVCAM FDIRFFVVCAM
INNER JOIN DPAIS DPAIS
ON DPAIS.CODPAIS = DPAIS.CODPAIS
INNER JOIN DREGIONCAMPANA DREGIONCAMPANA
ON DREGIONCAMPANA.ANIOCAMPANA = FDIRFFVVCAM.ANIOCAMPANA
AND DREGIONCAMPANA.PKREGION = FDIRFFVVCAM.PKREGION
INNER JOIN DROL DROL
ON DROL.PKROL = FDIRFFVVCAM.PKROL
INNER JOIN DCLIENTEFFVV DCLIENTEFFVV
ON DCLIENTEFFVV.PKClienteFFVV = FDIRFFVVCAM.PKClienteFFVV
INNER JOIN @TABLE_CAMPANAS TABLE_CAMPANAS
ON TABLE_CAMPANAS.ANIOCAMPANA = FDIRFFVVCAM.ANIOCAMPANA
WHERE FDIRFFVVCAM.DesPerfil = 'TITULAR'
AND DROL.CODROL = 'GR'

UNION

SELECT
	FDIRFFVVCAM.PKClienteFFVV
	,FDIRFFVVCAM.ANIOCAMPANA
	,DPAIS.CODPAIS
	,DZONACAMPANA.CODREGION
	,DZONACAMPANA.CODZONA
	,DROL.CODROL
	,DCLIENTEFFVV.CUB
	,DCLIENTEFFVV.codClienteFFVV
	,DCLIENTEFFVV.DesApeNom
FROM FDIRFFVVCAM FDIRFFVVCAM
INNER JOIN DPAIS DPAIS
ON DPAIS.CODPAIS = DPAIS.CODPAIS
INNER JOIN DZONACAMPANA DZONACAMPANA
ON DZONACAMPANA.ANIOCAMPANA = FDIRFFVVCAM.ANIOCAMPANA
AND DZONACAMPANA.PKREGION = FDIRFFVVCAM.PKREGION
AND DZONACAMPANA.PKZONA = FDIRFFVVCAM.PKZONA
INNER JOIN DROL DROL
ON DROL.PKROL = FDIRFFVVCAM.PKROL
INNER JOIN DCLIENTEFFVV DCLIENTEFFVV
ON DCLIENTEFFVV.PKClienteFFVV = FDIRFFVVCAM.PKClienteFFVV
INNER JOIN @TABLE_CAMPANAS TABLE_CAMPANAS
ON TABLE_CAMPANAS.ANIOCAMPANA = FDIRFFVVCAM.ANIOCAMPANA
WHERE FDIRFFVVCAM.DesPerfil = 'TITULAR'
AND DROL.CODROL = 'GZ';


SELECT A.PKClienteFFVV, MAX(A.ANIOCAMPANA) ANIOCAMPANA_ASIG
INTO #TEMP_CAMPANA_ASIG
FROM (
		SELECT
		PKClienteFFVV
		,DesRol
		,MIN(AnioCampana) AnioCampana
		FROM FDIRFFVVCAM
		WHERE DesPerfil = 'TITULAR'
		GROUP BY
		PKClienteFFVV
		,DesRol
	) A
GROUP BY A.PKClienteFFVV;



SELECT
TEMP_FFVV.ANIOCAMPANA
,TEMP_FFVV.CODPAIS
,TEMP_FFVV.CODREGION
,TEMP_FFVV.CODZONA
,TEMP_FFVV.CODROL
,TEMP_FFVV.CUB
,TEMP_FFVV.codClienteFFVV
,TEMP_FFVV.DesApeNom
,CASE
	WHEN ([dbo].[DiffAnioCampanas](TEMP_FFVV.ANIOCAMPANA,TEMP_CAMPANA_ASIG.ANIOCAMPANA_ASIG) +1) BETWEEN 1 AND 6 THEN 'NUEVA'
	WHEN ([dbo].[DiffAnioCampanas](TEMP_FFVV.ANIOCAMPANA,TEMP_CAMPANA_ASIG.ANIOCAMPANA_ASIG) +1) >= 7 THEN 'ESTABLE'
	ELSE ''
END AS [STATUS]
,([dbo].[DiffAnioCampanas](TEMP_FFVV.ANIOCAMPANA,TEMP_CAMPANA_ASIG.ANIOCAMPANA_ASIG) +1) NRO_ANIOCAMPANA_ASIG
FROM #TEMP_FFVV TEMP_FFVV
INNER JOIN #TEMP_CAMPANA_ASIG TEMP_CAMPANA_ASIG
ON TEMP_FFVV.PKClienteFFVV = TEMP_CAMPANA_ASIG.PKClienteFFVV;
