-- Creación de tablas para output

CREATE TABLE IF NOT EXISTS lan_virtual_coach.fdethybrysdata_v2
(
	addressregion VARCHAR(50)   ENCODE lzo
	,birthdate VARCHAR(50)   ENCODE lzo
	,calendaryear CHAR(4)   ENCODE lzo
	,campaignautomationactionuui VARCHAR(50)   ENCODE lzo
	,campaigncategory CHAR(5)   ENCODE lzo
	,campaigncontentlink VARCHAR(255)   ENCODE lzo
	,campaigncontentlinkgroup VARCHAR(100)   ENCODE lzo
	,campaigncontentlinkname VARCHAR(100)   ENCODE lzo
	,campaigncontentlinkurl VARCHAR(255)   ENCODE lzo
	,campaignexecutionstatus CHAR(3)   ENCODE lzo
	,campaignname VARCHAR(50)   ENCODE lzo
	,campaignowner CHAR(25)   ENCODE lzo
	,campaignpriority INTEGER   ENCODE lzo
	,campaignprocesstype CHAR(10)   ENCODE lzo
	,campaignversion INTEGER   ENCODE lzo
	,cityname VARCHAR(50)   ENCODE lzo
	,communicationcategory CHAR(25)   ENCODE lzo
	,communicationcategoryname VARCHAR(50)   ENCODE lzo
	,communicationmedium CHAR(20)   ENCODE lzo
	,companyname VARCHAR(100)   ENCODE lzo
	,contactpostalcode VARCHAR(25)   ENCODE lzo
	,country CHAR(2)   ENCODE lzo
	,currency NUMERIC(18,0)   ENCODE RAW
	,department VARCHAR(100)   ENCODE lzo
	,emailaddress VARCHAR(100)   ENCODE lzo
	,fullname VARCHAR(100)   ENCODE lzo
	,"function" VARCHAR(100)   ENCODE lzo
	,gendercode VARCHAR(255)   ENCODE lzo
	,id VARCHAR(256)   ENCODE lzo
	,interaction CHAR(40)   ENCODE lzo
	,interactionamount DOUBLE PRECISION   ENCODE runlength
	,interactioncontact VARCHAR(50)   ENCODE lzo
	,interactioncontactid VARCHAR(255)   ENCODE lzo
	,interactioncontent VARCHAR(255)   ENCODE lzo
	,interactioncontentsubject VARCHAR(50)   ENCODE lzo
	,interactionreason VARCHAR(50)   ENCODE lzo
	,interactionsourceobjectstat VARCHAR(20)   ENCODE lzo
	,interactiontimestamputc CHAR(50)   ENCODE lzo
	,interactiontype VARCHAR(50)   ENCODE lzo
	,interactionutcdate CHAR(25)   ENCODE lzo
	,interactionutctime CHAR(20)   ENCODE lzo
	,maritalstatus VARCHAR(20)   ENCODE lzo
	,marketingarea CHAR(25)   ENCODE lzo
	,marketingorchestrationid INTEGER   ENCODE bytedict
	,marketingprogram VARCHAR(50)   ENCODE lzo
	,marketingprogramid VARCHAR(50)   ENCODE lzo
	,marketingprogramname VARCHAR(100)   ENCODE lzo
	,mediatype VARCHAR(50)   ENCODE lzo
	,mobilenumber VARCHAR(30)   ENCODE lzo
	,nmbrofmisgmarketingpermissi INTEGER   ENCODE lzo
	,numberofanyclicks INTEGER   ENCODE lzo
	,numberofbounces INTEGER   ENCODE lzo
	,numberofdeliveredemailmessa INTEGER   ENCODE lzo
	,numberofdeliveredmessages INTEGER   ENCODE lzo
	,numberofemailcomplaints INTEGER   ENCODE lzo
	,numberofhardbounces INTEGER   ENCODE lzo
	,numberofinteractions INTEGER   ENCODE lzo
	,numberoflimitreached INTEGER   ENCODE lzo
	,numberofmarketingofferclick INTEGER   ENCODE lzo
	,numberofmissingcommdata INTEGER   ENCODE lzo
	,numberofopenedmessages INTEGER   ENCODE lzo
	,numberofsentmessages INTEGER   ENCODE lzo
	,numberofsoftbounces INTEGER   ENCODE lzo
	,numberoftotalclicks INTEGER   ENCODE lzo
	,numberofuniqueclicks INTEGER   ENCODE lzo
	,numberofuniqueopens INTEGER   ENCODE lzo
	,numberofunopenedmessages INTEGER   ENCODE lzo
	,rootinteraction VARCHAR(50)   ENCODE lzo
	,targetgroup INTEGER   ENCODE bytedict
	,targetgroupuuid VARCHAR(50)   ENCODE lzo
	,yy1_codigoebelista_mps VARCHAR(30)   ENCODE lzo
	,yy1_documentoidentidad_mps VARCHAR(30)   ENCODE lzo
	,yearmonth CHAR(6)   ENCODE lzo
	,yearquarter CHAR(5)   ENCODE lzo
	,yearweek CHAR(6)   ENCODE lzo
	,idcampanaconsultora VARCHAR(25)   ENCODE lzo
	,campaigncontentlinkaliasnam VARCHAR(256)   ENCODE lzo
	,campaignenddate CHAR(25)   ENCODE lzo
	,campaignstartdate CHAR(25)   ENCODE lzo
	,codigoconsultora CHAR(20)   ENCODE lzo
	,codigoebelista CHAR(30)   ENCODE lzo
	,codigopais CHAR(3)   ENCODE lzo
	,campanaexposicion CHAR(6)   ENCODE lzo
	,ebelista CHAR(30)   ENCODE lzo
	,numerocampanaexposicion CHAR(2)   ENCODE lzo
	,aniocampanaexposicion CHAR(4)   ENCODE lzo
	,campaignid CHAR(5)   ENCODE lzo
	,executionrundatetime CHAR(50)   ENCODE lzo
	,campaignexecutionrundate CHAR(25)   ENCODE lzo
	,recipientemaildomain VARCHAR(50)   ENCODE lzo
	,yy1_idconsultoracbo_mps VARCHAR(30)   ENCODE lzo
	,nombresocia VARCHAR(100)   ENCODE lzo
	,desseccion VARCHAR(100)   ENCODE lzo
	,codseccion VARCHAR(5)   ENCODE lzo
	,gerentezona VARCHAR(100)   ENCODE lzo
	,deszona VARCHAR(100)   ENCODE lzo
	,codzona INTEGER   ENCODE bytedict
	,desregion VARCHAR(100)   ENCODE lzo
	,codregion CHAR(2)   ENCODE lzo
	,flag100digital INTEGER   ENCODE bytedict
	,flaginscritaganamas INTEGER   ENCODE bytedict
	,flaginscritavirtualcoach INTEGER   ENCODE bytedict
	,flagappsocia INTEGER   ENCODE bytedict
	,flagappconsultora INTEGER   ENCODE bytedict
	,flagessocia INTEGER   ENCODE bytedict
	,fechaingresobelcorp CHAR(50)   ENCODE lzo
	,desaliasnombre VARCHAR(100)   ENCODE lzo
	,desdireccion VARCHAR(250)   ENCODE lzo
	,campanaingreso VARCHAR(6)   ENCODE lzo
	,flagcelular INTEGER   ENCODE bytedict
	,flagcorreo INTEGER   ENCODE bytedict
	,nrodocidentidad VARCHAR(25)   ENCODE lzo
	,tipodocumento VARCHAR(10)   ENCODE lzo
	,nrocampananuevas INTEGER   ENCODE bytedict
	,nropedidosnuevas INTEGER   ENCODE bytedict
	,fechapasepedido CHAR(25)   ENCODE lzo
	,fechafinfacturacion CHAR(25)   ENCODE lzo
	,fechainiciofacturacion CHAR(25)   ENCODE lzo
	,fechafinventa CHAR(25)   ENCODE lzo
	,fechainiciodeventa CHAR(25)   ENCODE lzo
	,flagdeuda INTEGER   ENCODE bytedict
	,flagpasopedido INTEGER   ENCODE bytedict
	,flagconstancianuevas INTEGER   ENCODE bytedict
	,flagtippingpoint4 INTEGER   ENCODE bytedict
	,flagtippingpoint5 INTEGER   ENCODE bytedict
	,flagtippingpoint6 INTEGER   ENCODE bytedict
	,flagofertadigitaluc INTEGER   ENCODE bytedict
	,nroofertadigitalpu5c INTEGER   ENCODE bytedict
	,flagipunicopu5c INTEGER   ENCODE bytedict
	,flagipunico INTEGER   ENCODE bytedict
	,desconstancianuevas VARCHAR(10)   ENCODE lzo
	,dessegmentodigital VARCHAR(100)   ENCODE lzo
	,descomportamiento VARCHAR(25)   ENCODE lzo
	,tipoconsultora CHAR(1)   ENCODE lzo
	,idcontactoconsultoracbo VARCHAR(25)   ENCODE lzo
	,idcontacto VARCHAR(25)   ENCODE lzo
	,idorigencontacto VARCHAR(50)   ENCODE lzo
)
DISTSTYLE EVEN;

--Segunda tabla backup
CREATE TABLE IF NOT EXISTS fnc_virtual_coach.fdethybrysdata
(
	addressregion VARCHAR(256)   ENCODE lzo
	,birthdate DATE   ENCODE lzo
	,calendaryear VARCHAR(256)   ENCODE lzo
	,campaignautomationactionuuid VARCHAR(256)   ENCODE lzo
	,campaigncategory VARCHAR(256)   ENCODE lzo
	,campaigncontentlink VARCHAR(256)   ENCODE lzo
	,campaigncontentlinkgroup VARCHAR(256)   ENCODE lzo
	,campaigncontentlinkname VARCHAR(256)   ENCODE lzo
	,campaigncontentlinkurl VARCHAR(256)   ENCODE lzo
	,campaignexecutionstatus VARCHAR(256)   ENCODE lzo
	,campaignid VARCHAR(256)   ENCODE lzo
	,campaignname VARCHAR(256)   ENCODE lzo
	,campaignowner VARCHAR(256)   ENCODE lzo
	,campaignpriority VARCHAR(256)   ENCODE lzo
	,campaignprocesstype VARCHAR(256)   ENCODE lzo
	,campaignversion VARCHAR(256)   ENCODE lzo
	,cityname VARCHAR(256)   ENCODE lzo
	,communicationcategory VARCHAR(256)   ENCODE lzo
	,communicationcategoryname VARCHAR(256)   ENCODE lzo
	,communicationmedium VARCHAR(256)   ENCODE lzo
	,companyname VARCHAR(256)   ENCODE lzo
	,contactpostalcode VARCHAR(256)   ENCODE lzo
	,country VARCHAR(5)   ENCODE lzo
	,currency VARCHAR(256)   ENCODE lzo
	,department VARCHAR(256)   ENCODE lzo
	,emailaddress VARCHAR(256)   ENCODE lzo
	,fullname VARCHAR(256)   ENCODE lzo
	,"function" VARCHAR(256)   ENCODE lzo
	,gendercode VARCHAR(256)   ENCODE lzo
	,id VARCHAR(256)   ENCODE lzo
	,interaction VARCHAR(256)   ENCODE lzo
	,interactionamount VARCHAR(256)   ENCODE lzo
	,interactioncontact VARCHAR(256)   ENCODE lzo
	,interactioncontactid VARCHAR(256)   ENCODE lzo
	,interactioncontent VARCHAR(256)   ENCODE lzo
	,interactioncontentsubject VARCHAR(256)   ENCODE lzo
	,interactionreason VARCHAR(256)   ENCODE lzo
	,interactionsourceobjectstatus VARCHAR(256)   ENCODE lzo
	,interactiontimestamputc DATE   ENCODE lzo
	,interactiontype VARCHAR(256)   ENCODE lzo
	,interactionutcdate DATE   ENCODE lzo
	,interactionutctime VARCHAR(256)   ENCODE lzo
	,maritalstatus VARCHAR(256)   ENCODE lzo
	,marketingarea VARCHAR(256)   ENCODE lzo
	,marketingorchestrationid VARCHAR(256)   ENCODE lzo
	,marketingprogram VARCHAR(256)   ENCODE lzo
	,marketingprogramid VARCHAR(256)   ENCODE lzo
	,marketingprogramname VARCHAR(256)   ENCODE lzo
	,mediatype VARCHAR(256)   ENCODE lzo
	,mobilenumber VARCHAR(256)   ENCODE lzo
	,nmbrofmisgmarketingpermissions VARCHAR(256)   ENCODE lzo
	,numberofanyclicks VARCHAR(256)   ENCODE lzo
	,numberofbounces VARCHAR(256)   ENCODE lzo
	,numberofdeliveredemailmessages VARCHAR(256)   ENCODE lzo
	,numberofdeliveredmessages VARCHAR(256)   ENCODE lzo
	,numberofemailcomplaints VARCHAR(256)   ENCODE lzo
	,numberofhardbounces VARCHAR(256)   ENCODE lzo
	,numberofinteractions VARCHAR(256)   ENCODE lzo
	,numberoflimitreached VARCHAR(256)   ENCODE lzo
	,numberofmarketingofferclicks VARCHAR(256)   ENCODE lzo
	,numberofmissingcommdata VARCHAR(256)   ENCODE lzo
	,numberofopenedmessages VARCHAR(256)   ENCODE lzo
	,numberofsentmessages VARCHAR(256)   ENCODE lzo
	,numberofsoftbounces VARCHAR(256)   ENCODE lzo
	,numberoftotalclicks VARCHAR(256)   ENCODE lzo
	,numberofuniqueclicks VARCHAR(256)   ENCODE lzo
	,numberofuniqueopens VARCHAR(256)   ENCODE lzo
	,numberofunopenedmessages VARCHAR(256)   ENCODE lzo
	,rootinteraction VARCHAR(256)   ENCODE lzo
	,targetgroup VARCHAR(256)   ENCODE lzo
	,targetgroupuuid VARCHAR(256)   ENCODE lzo
	,yy1_codigoebelista_mps VARCHAR(256)   ENCODE lzo
	,yy1_documentoidentidad_mps VARCHAR(256)   ENCODE lzo
	,yearmonth VARCHAR(256)   ENCODE lzo
	,yearquarter VARCHAR(256)   ENCODE lzo
	,yearweek VARCHAR(256)   ENCODE lzo
	,flagfechacorrecta SMALLINT   ENCODE lzo
	,aniocampana VARCHAR(6)   ENCODE lzo
)
DISTSTYLE EVEN
INTERLEAVED SORTKEY (
	country
	, interactiontimestamputc
	);